### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by Bluscream** [BluscreamFanBoy/multistreamchat#4]
```python
C:\Users\blusc_000\Documents\GitHub\multistreamchat>python main.py                                     
Exception in thread Thread-1:                                                                          
Traceback (most recent call last):                                                                     
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py                     
", line 914, in _bootstrap_inner                                                                       
    self.run()                                                                                         
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py                     
", line 862, in run                                                                                    
    self._target(*self._args, **self._kwargs)                                                          
  File "C:\Users\blusc_000\Documents\GitHub\multistreamchat\apps\beampro.py", line                     
 76, in run_msgs_collector                                                                             
    name = nmsg["user_name"]                                                                           
TypeError: string indices must be integers                                                             
                                                                                                       
Exception in thread Thread-2:                                                                          
Traceback (most recent call last):                                                                     
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py                     
", line 914, in _bootstrap_inner                                                                       
    self.run()                                                                                         
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py                     
", line 862, in run                                                                                    
    self._target(*self._args, **self._kwargs)                                                          
  File "C:\Users\blusc_000\Documents\GitHub\multistreamchat\apps\twitch.py", line                      
80, in run_follower_collector                                                                          
    pageurl = jso_follows["_links"]["next"]                                                            
KeyError: '_links'                                                                                     
                                                                                                       
Exception in thread Thread-4:                                                                          
Traceback (most recent call last):                                                                     
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _boot
strap_inner                                                                                            
    self.run()                                                                                         
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run  
    self._target(*self._args, **self._kwargs)                                                          
  File "C:\Users\blusc_000\Documents\GitHub\multistreamchat\apps\hitbox.py", line 66, in run_msgs_colle
ctor                                                                                                   
    resp = json.loads(resp[4:])                                                                        
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in l
oads                                                                                                   
    return _default_decoder.decode(s)                                                                  
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in de
code                                                                                                   
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                  
  File "C:\Users\blusc_000\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in ra
w_decode                                                                                               
    raise JSONDecodeError("Expecting value", s, err.value) from None                                   
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                
```

**Comment by FlorianSteenbuck** [comment]
Can you provide more info about your config files and your setup. This could be a problem if one service is active but not proudly right configured. I dont have written a check for the config yet

**Comment by Bluscream** [comment]
I will post them redacted as soon as possible :)

**Comment by FlorianSteenbuck** [comment]
Find a solution yet. I can not reproduce the error. Got no device. Also twitch api changed much. I think I need a complete new update.

still got problems with my live so this would take time

**Comment by Bluscream** [comment]
Oh im sorry for you and hope you can fix ur life soon <3

**Comment by FlorianSteenbuck** [comment]
😀
